server:
  port: xxxxxxx

  ssl:
    key-store: xxxxx
    key-store-password: xxxxxx
    key-store-type: JKS

spring:
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  application:
    name: huahuo-bank
  cache:
    redis:
      time-to-live: 1800000
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: xxxxxx
      username: xxxxx
      password: xxxxx

#
#  redis:
#    host: tycloud.fzuhuahuo.cn
#    port: 6379
#    #password: 123456
#    database: 0 #????0????
#    jedis:
#      #Redis?????
#      pool:
#        max-active: 8 #?????
#        max-wait: 1ms #???????????
#        max-idle: 4 #???????????
#        min-idle: 0 #???????????

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

